before_script:
  - | # derive and print WS_JOBS
      export WS_JOBS=${CI_RUNNER_DESCRIPTION##*-j} # strip the longest match of *-j from the front of the description
      if [[ "$WS_JOBS" = "$CI_RUNNER_DESCRIPTION" ]] ; then # check if no match happened
        WS_JOBS=0
      else
        case "${WS_JOBS}" in
          ''|*[!0-9]*) WS_JOBS=0 ;; # check if remaining value is not a number
        esac
      fi
      echo "WS_JOBS=${WS_JOBS}"

variables:
  SCCACHE_CACHE_SIZE: 100G
  CARGO_HOME: /cache/cargo

stages:
  - test

sample:
  stage: test
  image: kleenet.comsys.rwth-aachen.de/symbiosys-projects-workspace-docker-base-image:latest
  script:
    - 'g++ -std=c++17 -Og -ggdb -fsanitize=address,undefined sample.cpp -DPSEUDOALLOC_CHECKED -o sample'
    - './sample'

randomtest:
  stage: test
  image: kleenet.comsys.rwth-aachen.de/symbiosys-projects-workspace-docker-base-image:latest
  script:
    - 'g++ -std=c++17 -Og -ggdb -fsanitize=address,undefined randomtest.cpp -DPSEUDOALLOC_CHECKED -DUSE_PSEUDOALLOC -o randomtest'
    - './randomtest'
